module.exports = {
  collector: {
    type: 'local',
    repositoryPath: process.env.LH_PATH,
  },
  collection: {
    runs: 25,
    urls: [
      // The original set of URLs
      // These URLs are too stable for our variance-focus
      // 'http://localhost:10200/online-only.html',
      // 'http://localhost:10200/perf/fonts.html',
      // 'http://localhost:10200/byte-efficiency/tester.html',
      // 'http://localhost:10200/a11y/a11y_tester.html',
      // 'https://example.com',
      // 'https://www.wikipedia.org',

      'https://www.amazon.com',
      'https://www.att.com',
      'https://www.cnet.com',
      'https://www.cnn.com',
      'https://www.facebook.com',
      'https://www.hulu.com',
      'https://www.linkedin.com',
      'https://www.sfgate.com',
      'https://www.theverge.com',
      'https://www.vevo.com',

      // The more variable URLs
      'http://www.bing.com',
      'http://www.blogspot.com',
      'http://www.craigslist.org',
      'http://www.dawn.com',
      'http://www.domaintools.com',
      'http://www.ebay.com',
      'http://www.espn.com',
      'http://www.foxnews.com',
      'http://www.hp.com',
      'http://www.huffingtonpost.com',
      'http://www.imageshack.us',
      'http://www.irs.gov',
      'http://www.java.com',
      'http://www.livedoor.jp',
      'http://www.liveperson.net',
      'http://www.mail.ru',
      'http://www.metacafe.com',
      'http://www.metrolyrics.com',
      'http://www.mlb.com',
      'http://www.mozilla.org',
      'http://www.msn.com',
      'http://www.netflix.com',
      'http://www.nih.gov',
      'http://www.nokia.com',
      'http://www.orange.fr',
      'http://www.orkut.com',
      'http://www.partypoker.com',
      'http://www.rakuten.co.jp',
      'http://www.scribd.com',
      'http://www.skype.com',
      'http://www.softonic.com',
      'http://www.symantec.com',
      'http://www.thefreedictionary.com',
      'http://www.tumblr.com',
      'http://www.twitpic.com',
      'http://www.typepad.com',
      'http://www.verizonwireless.com',
    ],
  },
  storage: {
    type: 'sql',
    host: '{{ hostvars[groups["masters"][0]].ansible_default_ipv4.address }}',
  },
  lighthouseConfig: {
    extends: 'lighthouse:default',
    settings: {onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo', 'pwa']},
  },
}
